### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sh1va73** [blueudp/Deep-Explorer#5]
I do a search and then it finds some results but then i get this error:

Not enought links in browser, crawling...
Traceback (most recent call last):
  File "deepexplorer.py", line 255, in <module>
    search(crawld, intext)
  File "deepexplorer.py", line 185, in search
    crawl("default", darklinks, intexts)
TypeError: crawl() missing 1 required positional argument: 'intexts'

**Comment by blueudp** [comment]
will check it asap

**Comment by abysswalker84** [comment]
I got error : Error creating 'soup' object
Ubuntu 20.04.2 LTS
